const quotes = [
    "romanticizing your life is a power move ✨",
    "you are the main character, act like it 🎬",
    "slow progress is still progress ☁️",
    "everything is working out for you 🕊️",
    "be soft but unstoppable 🌊",
    "your future self will thank you 💌",
    "stay consistent, it will pay off 📈",
    "protect your energy at all costs 🧿",
    "bloom where you are planted 🌸",
    "radiate kindness like sunshine ☀️",
    "collecting moments, not things 🎞️",
    "your potential is limitless 🚀",
    "don't forget to breathe 🌿",
    "be the reason someone smiles today 🌈",
    "manifesting big dreams only 🕯️",
    "focus on the good vibes 🦋",
    "you are enough, always 🩰",
    "trust the timing of your life ⏳",
    "stay cozy and keep dreaming 🧸",
    "create your own sunshine 🎨",
    "life is better when you're laughing 🍯",
    "keep going, you're doing great 🧸",
    "magic happens outside your comfort zone 🌌",
    "be your own best friend 🍦",
    "small steps lead to big changes 👣",
    "your vibe attracts your tribe 🧚",
    "embrace the glorious mess that you are 🧁",
    "do it for your future self 💎",
    "life is a series of tiny miracles 🍀",
    "believe in your own magic 🪄",
    "stay wild, moon child 🌙",
    "you are capable of amazing things 🌟",
    "kindness is always in style 👗",
    "choose joy every single day 🎈",
    "keep your head in the clouds ☁️",
    "be a starlight in someone's dark 💫",
    "growth looks good on you 🌱",
    "it's okay to take a break ☕",
    "make today beautiful 🐚",
    "listen to your heart's rhythm 🎶",
    "you're rare and valuable 🔮",
    "stay hungry, stay foolish 🍎",
    "keep shining, the world needs your light 💡",
    "happiness is an inside job 🏠",
    "don't just exist, live 🌍",
    "be a voice, not an echo 📣",
    "chase the sunset, not the person 🌇",
    "self-love is the best love 💖",
    "your life is your canvas 🖌️",
    "the best is yet to come 🥂"
];

function generateQuote() {
    let randomIndex=Math.floor(Math.random() * quotes.length);
    document.getElementById("quote").innerText=quotes[randomIndex];
}